# Generated by Django 6.0.4 on 2026-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calendar_app', '0003_event_is_global_event_users_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
